{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
data:
  geoserver_admin_password: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
