apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: geoserver
      protocol: TCP
      name: geoserver
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
