apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "incore.fullname" . }}-doc-api
  labels:
    {{- include "incore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.doc_api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "incore.name" . }}-doc-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "incore.name" . }}-doc-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: doc-api
          image: "{{ .Values.image.project }}/{{ .Values.doc_api.image.repository }}:{{ .Values.doc_api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.doc_api.resources | nindent 12 }}
      {{- with .Values.doc_api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.doc_api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.doc_api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
