{{- if .Values.monitor.enabled }}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "clowder.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-monitor
  labels:
{{ include "clowder.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
{{- if .Values.ingress.hosts }}
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}monitor/
            backend:
              serviceName: {{ $fullName }}-monitor
              servicePort: monitor
  {{- end }}
{{- else }}
    - http:
        paths:
          - path: {{ $.Values.ingress.path }}monitor/
            backend:
              serviceName: {{ $fullName }}-monitor
              servicePort: monitor
{{- end }}
{{- end }}
{{- end }}
