apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["mlflow"]
          env:
              {{- if .Values.postgresql.auth.existingSecret }}
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.postgresql.auth.existingSecret }}
                    key: password
              {{- end }}
              - name: MLFLOW_S3_ENDPOINT_URL
                value: "http://{{ .Release.Name }}-minio:{{ .Values.minio.service.ports.api }}"
            {{- if .Values.minio.auth.existingSecret }}
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.minio.auth.existingSecret }}
                    key: root-user
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.minio.auth.existingSecret }}
                    key: root-password
            {{- else }}
              - name: AWS_ACCESS_KEY_ID
                value: "{{ .Values.minio.auth.rootUser }}"
              - name: AWS_SECRET_ACCESS_KEY
                value: "{{ .Values.minio.auth.rootPassword }}"
            {{- end }}
          args: ["server",
                 "--backend-store-uri", "{{- template "services.postgres.uri" .}}",
                 "--default-artifact-root", "{{- template "services.minio.uri" . }}",
                 "--host", "0.0.0.0"]
          ports:
            - name: mlflow
              containerPort: 5000
              protocol: TCP
#          livenessProbe:
#            initialDelaySeconds: 45
#            httpGet:
#              path: /
#              port: mlflow
#          readinessProbe:
#            initialDelaySeconds: 45
#            httpGet:
#              path: /
#              port: mlflow
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
