apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mlflow
      protocol: TCP
      name: mlflow
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
