apiVersion: v2
name: fah
description: Folding@Home - Distributed computing for disease research
type: application
version: 1.1.0
appVersion: 8.5.5
home: https://foldingathome.org/
icon: https://foldingathome.org/wp-content/uploads/2016/08/cropped-folding-at-home-logo.png
maintainers:
  - name: Rob Kooper
    email: kooper@illinois.edu
  - name: Christopher Heller
    email: cheller@illinois.edu
annotations:
  artifacthub.io/changes: |
    - Updated Fah from 8.4.9 to 8.5.5
