apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clowder.fullname" . }}
  labels:
{{ include "clowder.labels" . | indent 4 }}
type: Opaque
data:
  clowder-key:  {{ required "Need to provide a key for clowder (commKey)" .Values.commKey | b64enc | quote }}
{{- if .Values.secretKey }}
  clowder-secret:  {{ .Values.secretKey | b64enc | quote }}
{{- else }}
  clowder-secret: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}
{{- if .Values.users }}
  {{- range $index, $element := .Values.users }}
    {{- if .password }}
  password-{{ $index }}: {{ .password | b64enc | quote }}
    {{- else }}
  password-{{ $index }}: {{ randAlphaNum 10 | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.rabbitmq.enabled }}
  rabbitmq-uri: {{ include "clowder.rabbitmquri" . | b64enc | quote }}
{{- end }}
  mongodb-uri: {{ include "clowder.mongodburi" . | b64enc | quote }}
{{- if .Values.storage.s3 }}
  s3-access-key: {{ .Values.storage.s3.access_key | b64enc | quote }}
  s3-secret-key: {{ .Values.storage.s3.secret_key | b64enc | quote }}
{{- end }}
